export const data = [
    {
        userId: "1121",
        name: "Charvie Sharma",
        img: "user1.jpg",
        email: "charsharma@gmail.com",
        stepsWalked: 2547,
        stepsTarget: 4000,
        performedDate: "15 Oct",
        scheduledDate: "22 Oct",
        calorieIntake: 2547,
        calorieTarget: 2500,
        proteinConsumed: 45,
        proteinTarget: 70,
        carbConsumed: 30,
        carbTarget: 70,
        fatConsumed: 50,
        fatTarget: 70,
        feedback: false
    },
    {
        userId: "1122",
        name: "Evan Budway",
        img: "user2.jpg",
        email: "evanbudway@gmail.com",
        stepsWalked: 3447,
        stepsTarget: 5500,
        performedDate: "15 Jan",
        scheduledDate: "22 Mar",
        calorieIntake: 2747,
        calorieTarget: 3000,
        proteinConsumed: 55,
        proteinTarget: 80,
        carbConsumed: 40,
        carbTarget: 60,
        fatConsumed: 20,
        fatTarget: 50,
        feedback: false
    },
    {
        userId: "1123",
        name: "Jettie Knelsen",
        img: "user3.jpg",
        email: "jettieknelsen@gmail.com",
        stepsWalked: 3447,
        stepsTarget: 5300,
        performedDate: "22 Apr",
        scheduledDate: "27 June",
        calorieIntake: 3547,
        calorieTarget: 3000,
        proteinConsumed: 75,
        proteinTarget: 100,
        carbConsumed: 40,
        carbTarget: 80,
        fatConsumed: 50,
        fatTarget: 60,
        feedback: false
    },
]